---
swagger: '2.0'
info:
  version: '1.0'
  title: High Performance Building Database
  description: 'The Buildings Database is a shared resource for the building industry.
    The Database, developed by the U.S. Department of Energy and the National Renewable
    Energy Laboratory (NREL), is a unique central repository of in-depth information
    and data on high-performance, green building projects across the United States
    and abroad.  '
paths:
  "/project.{output_format}":
    get:
      responses:
        '200':
          description: Successful request
      description: ''
      tags:
      - project.json
      summary: A filterable list of projects.
      operationId: project
      produces:
      - text/xml
      parameters:
      - in: path
        description: Response Format
        name: output_format
        required: true
        type: string
        default: xml
        enum:
          - json
          - xml
      - in: query
        description: API Key
        name: api_key
        required: true
        type: string
        default: DEMO_KEY
      - in: query
        description: Search Text
        name: search
        required: false
        type: string
      - in: query
        description: Portal ID
        name: portal
        required: false
        type: string
      - in: query
        description: Page Number
        name: page
        required: false
        type: integer
      - in: query
        description: City
        name: city
        required: false
        type: string
      - in: query
        description: 'State or Province (ex: ''CO'', ''AZ'')'
        name: province
        required: false
        type: string
      - in: query
        description: 'Climate Region.  Use integer from mapping (256: ''1A: Very Hot
          - Humid'', 257: ''1B: Very Hot - Dry'', 258: ''2A: Hot - Humid'', 259: ''2B:
          Hot - Dry'', 260: ''3A: Warm - Humid'', 261: ''3B: Warm - Dry'', 262: ''3C:
          Warm - Marine'', 263: ''4A: Mixed - Humid'', 264: ''4B: Mixed - Dry'', 265:
          ''4C: Mixed - Marine'', 266: ''5A: Cool - Humid'', 267: ''5B: Cool - Dry'',
          268: ''5C: Cool - Marine'', 269: ''6A: Cold - Humid'', 270: ''6B: Cold -
          Dry'', 271: ''7: Very Cold'', 272: ''8: Subarctic'')'
        name: region
        required: false
        type: string
  "/project/{project_id}.{output_format}":
    get:
      responses:
        '200':
          description: Successful request
      description: ''
      tags:
      - project.json
      summary: Project Details
      operationId: document
      produces:
      - text/xml
      parameters:
      - in: path
        description: Response Format
        name: output_format
        required: true
        type: string
        default: json
        enum:
          - json
          - xml
      - in: query
        description: API Key
        name: api_key
        required: true
        type: string
        default: DEMO_KEY
      - in: path
        description: Project ID
        name: project_id
        required: true
        type: integer
basePath: "/api/building-case-studies"
tags:
- name: project.json
  description: API endpoints related to buildings.
schemes:
- https
