swagger: "2.0"
info:
  version: "1"
  title: Facilities APIs
  description: |-
    A collection of APIs providing data about national laboratorty facilities associated with the Department of Energy's (DOE) Lab Partnering Service (LPS).
schemes:
- https
basePath: /
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: query
security:
- api_key: []
paths:
  /api/lps/v{version}/facilities:
    get:
      summary: Returns a paginated list of all national laboratory facilities
      parameters:
        - in: path
          name: version
          type: integer
          required: true
          description: API version, only current option is 1
        - in: query
          name: limit
          type: integer
          required: false
          description: Number of results to return, default is 25, max is 200; to receive more than <i>limit</i> number of results, increment page param in subsequent requests.
        - in: query
          name: page
          type: integer
          required: false
          description: Page number of results, default is 0; see limit
      responses:
        200:
          description: Successful request
          schema:
            $ref: "#/definitions/facilities_response"
          examples:
            Valid:
              metadata: {"version": 1}
              inputs: {}
              errors: {}
              resultset: {
                "total": 167,
                "count": 25,
                "number": 0,
                "pages": 7,
                "result": [
                {
                "uuid": "40941550-a3d7-4e33-9f5c-5503cdaf70d7",
                "name": "Dynamical Nuclear Polarization NMR Facility",
                "alias": "dnp-nmr",
                "description": "The Ames Laboratory is home to the United States' first dynamic nuclear polarization (DNP) solid-state nuclear magnetic resonance (NMR) spectrometer dedicated to the study of materials science and chemistry. NMR is used to determine the structure of solid materials on the atomic scale but this method is hindered by intrinsically low sensitivity as the instrument is not able to pick up the small signals of the nuclei under study. DNP helps overcome NMR's shortcomings by boosting sensitivity by up to 100 times. An exponential increase in sensitivity means researchers can take data 10,000 times faster, shortening collection times from weeks down to under an hour.",
                "user_facility": false,
                "labs": [
                {
                "uuid": "facca896-d97c-4a47-8260-7e75539f4010",
                "name": "Ames Laboratory",
                "tto_url": "https://www.ameslab.gov/techtransfer",
                "contact_us_email": "ameslps@ameslab.gov",
                "links": {"self": "https://developer.nrel.gov/api/lps/v1/labs/facca896-d97c-4a47-8260-7e75539f4010"}
                }
                ],
                "links": {"self": "https://developer.nrel.gov/api/lps/v1/facilities/40941550-a3d7-4e33-9f5c-5503cdaf70d7"}
                },
                {
                "uuid": "fc0baef1-e69e-4126-a7ae-5d5a73f58132",
                "name": "Materials Preparation Center",
                "alias": "123456789012",
                "description": "MPC is recognized throughout the worldwide research community for its unique capabilities in purification, preparation, and characterization of: rare earth metals, single crystal growth, metal powders/atomization, alkaline-earth metals, and refractory metal. Established in 1981, the MPC is a one-of-a-kind facility, which is acutely sensitive to the needs of researchers. Providing research and developmental quantities of high-purity materials and unique characterization services to scientists at university, industry and government facilities on a cost-recovery basis, the MPC allows access to novel materials and new technologies as they are developed.<br>Work requests through the MPC will be handled by the MPC Terms and Conditions agreement.",
                "user_facility": false,
                "labs": [
                {
                "uuid": "facca896-d97c-4a47-8260-7e75539f4010",
                "name": "Ames Laboratory",
                "tto_url": "https://www.ameslab.gov/techtransfer",
                "contact_us_email": "ameslps@ameslab.gov",
                "links": {"self": "https://developer.nrel.gov/api/lps/v1/labs/facca896-d97c-4a47-8260-7e75539f4010"}
                }
                ],
                "links": {"self": "https://developer.nrel.gov/api/lps/v1/facilities/fc0baef1-e69e-4126-a7ae-5d5a73f58132"}
                }
                ]
                }
            Invalid:
              metadata: {"version": 1}
              inputs: {"version": 2}
              errors: {"status": 400, "detail": "unsupported version"}
              resultset: []
  /api/lps/v{version}/facilities/{facility_uuid}:
    get:
      summary: Returns detailed information about one national laboratory facility
      parameters:
      - in: path
        name: version
        type: integer
        required: true
        description: API version, only current option is 1
      - in: path
        name: facility_uuid
        type: string
        required: true
        description: Unique identifer for a Facility
      responses:
        200:
          description: Successful request
          schema:
            $ref: "#/definitions/facilities_response"
          examples:
            Valid:
              metadata: {"version": 1}
              inputs: {"uuid": "0dde3661-0bf7-4241-9074-7b19136565a0"}
              errors: {}
              resultset: {
                "total": 1,
                "count": 1,
                "number": 0,
                "pages": 1,
                "result": [
                {
                "uuid": "0dde3661-0bf7-4241-9074-7b19136565a0",
                "name": "Powder Synthesis and Development Facility",
                "alias": "psdf",
                "description": "The Powder Synthesis and Development Facility (PSDF) is dedicated to expanding the use and application of metallic powders through understanding the fundamental characteristics of the powder synthesis process and scientific/metallurgical alloy development. Primarily powder is produced via close-coupled gas atomization, in our experimental scale (2-5kg) and pilot scale (10-25kg) atomization systems. <br>Ames Laboratory PSDF produces custom powder metals which cannot be purchased from commercial suppliers in small and pilot-scale powder batches for external parties through DOE's Strategic Partnership Projects. PSDF also can conduct assessments of powder submitted to the facility. ",
                "user_facility": false,
                "labs": [
                {
                "uuid": "facca896-d97c-4a47-8260-7e75539f4010",
                "name": "Ames Laboratory",
                "tto_url": "https://www.ameslab.gov/techtransfer",
                "contact_us_email": "ameslps@ameslab.gov",
                "links": {"self": "https://developer.nrel.gov/api/lps/v1/labs/facca896-d97c-4a47-8260-7e75539f4010"}
                }
                ],
                "links": {"self": "https://developer.nrel.gov/api/lps/v1/facilities/0dde3661-0bf7-4241-9074-7b19136565a0"}
                }
                ]
                }
            Invalid:
              metadata: {"version": 1}
              inputs: {"version": 2}
              errors: {"status": 400, "detail": "unsupported version"}
              resultset: []
  /api/lps/v{version}/facilities/lab/{lab_alias}:
    get:
      summary: Returns detailed information about a specific national laboratory facility
      parameters:
        - in: path
          name: version
          type: integer
          required: true
          description: API version, only current option is 1
        - in: path
          name: lab_alias
          type: string
          required: true
          description: An alias for a national laboratory in LPS
      responses:
        200:
          description: Successful request
          schema:
            $ref: "#/definitions/lab_facilities_response"
          examples:
            Valid:
              metadata: {"version": 1}
              inputs: {"alias": "emf"}
              errors: {}
              resultset: {
                "total": 1,
                "count": 1,
                "number": 0,
                "pages": 1,
                "result": [
                {
                "uuid": "8c23ee2b-fc02-45ca-8ca8-3a3d860b3916",
                "name": "Electron Microscopy Facility",
                "alias": "emf",
                "description": "<p>This facility consists of four top-of-the line transmission electron microscopes, two of which are highly specialized instruments capable of extreme levels of resolution, achieved through spherical aberration correction. The facility is also equipped with extensive sample-preparation capabilities. </p><p><br></p><p>The scientific interests of the staff focus on understanding the microscopic origin of the physical and chemical behavior of materials, with specific emphasis on in-situ studies of materials in native, functional environments.</p>",
                "user_facility": true,
                "labs": [
                {
                "uuid": "b9bb03a5-2c32-4cba-a2e3-024938bcba78",
                "name": "Brookhaven National Laboratory",
                "tto_url": "https://www.bnl.gov/techtransfer/ ",
                "contact_us_email": "tech@bnl.gov",
                "links": {"self": "https://developer.nrel.gov/api/lps/v1/labs/b9bb03a5-2c32-4cba-a2e3-024938bcba78"}
                }
                ],
                "links": {"self": "https://developer.nrel.gov/api/lps/v1/facilities/8c23ee2b-fc02-45ca-8ca8-3a3d860b3916"}
                }
                ]
                }
            Invalid:
              metadata: {"version": 1}
              inputs: {"version": 2}
              errors: {"status": 400, "detail": "unsupported version"}
              resultset: []
definitions:
  metadata:
    type: object
    properties:
      version:
        type: integer
        example: 1
  inputs:
    type: object
    properties:
      input_name:
        type: string
  errors:
    type: object
    properties:
      status:
        type: integer
      detail:
        type: string
  facility:
    type: object
    properties:
      uuid:
        type: string
        example: '0dde3661-0bf7-4241-9074-7b19136565a0'
      name:
        type: string
        example: 'Powder Synthesis and Development Facility'
      alias:
        type: string
        example: emf
      description:
        type: string
        example: MPC is recognized throughout the worldwide research community for its unique capabilities etc
      user_facility:
        type: boolean
        example: false
      labs:
        type: array
        items:
          properties:
            uuid:
              type: string
              example: facca896-d97c-4a47-8260-7e75539f4010
            name:
              type: string
              example: Ames Laboratory
            tto_url:
              type: string
              example: "https://www.ameslab.gov/techtransfer"
            contact_us_email:
              type: string
              example: "ameslps@ameslab.gov"
            links:
              type: array
              items:
                properties:
                  self:
                    type: string
                    example: "https://developer.nrel.gov/api/lps/v1/labs/facca896-d97c-4a47-8260-7e75539f4010"
      links:
        type: object
        properties:
          self:
            type: string
            example: "https://developer.nrel.gov/api/lps/v1/facilities/0dde3661-0bf7-4241-9074-7b19136565a0"
  facilities:
    type: array
    items:
      $ref: "#/definitions/facility"
  facilities_response:
    type: object
    properties:
      metadata:
        type: object
        $ref: "#/definitions/metadata"
      inputs:
        type: object
        $ref: "#/definitions/inputs"
      errors:
        type: object
        $ref: "#/definitions/errors"
      resultset:
        type: object
        properties:
          total:
            type: integer
            example: 20000
            description: Total number of records which meet the search criteria
          count:
            type: integer
            example: 20
            description: The number of records in a single response
          number:
            type: integer
            example: 1
            description: The current page number of paginated responses
          pages:
            type: integer
            example: 39
            description: The total number of pages in the paginated responses
          result:
            type: object
            $ref: "#/definitions/facilities"
  lab_facilities_response:
    type: object
    properties:
      metadata:
        type: object
        $ref: "#/definitions/metadata"
      inputs:
        type: object
        $ref: "#/definitions/inputs"
      errors:
        type: object
        $ref: "#/definitions/errors"
      resultset:
        type: object
        properties:
          result:
            type: object
            $ref: "#/definitions/facilities"
